package leetcode

/*Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/find-the-difference
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。*/

func findTheDifference(s string, t string) byte {
	sMap := [26]int{}
	tMap := [26]int{}
	for i := 0; i < len(s); i++ {
		sMap[int(s[i]-'a')]++
		tMap[int(t[i]-'a')]++
	}
	tMap[int(t[len(t)-1]-'a')]++
	for i := 0; i < 26; i++ {
		if sMap[i] != tMap[i] {
			return 'a' + byte(i)
		}
	}
	return '#'
}
